### ISSUE TITLE
[bug] 浏览器访问docker容器中运行 easytier-web-embed的web注册页面无法显示验证码

### ISSUE THREAD

**Issue by axlrose** [EasyTier/EasyTier#1037]
### 描述问题 / Describe the bug

测试结论: docker中容器环境导致无法正常显示图片

1. 测试步骤 
2. docker中运行的版本为 easytier-web 2.3.2-42c98203
3. win11下使用firefox浏览器访问无法显示验证码图片，同时访问win11下的 easytier-web-embed.exe 可以正常显示验证码图片
4. 在linux下单独运行 github release下载的 easytier-web-embed 也可以正常显示验证码图片
5. docker cp easytier-web:/usr/local/bin/easytier-web-embed ./> 下载docker中的easytier-web-embed 后运行，再通过浏览器访问可以正常显示图片，排除 bin文件问题，应该是docker容器环境问题

5. 以下为docker compose文件 
```yaml
services:
  easytier-web:
    container_name: easytier-web
      #network_mode: host
    network_mode: bridge
    volumes:
      - /vol1/1000/docker/easytier-web/etc/easytier:/etc/easytier/
      - /etc/machine-id:/etc/machine-id:ro # 映射宿主机机器码

    environment:
      - TZ=Asia/Shanghai

    image: easytier/easytier:latest
    entrypoint: ["/sbin/tini", "--", "easytier-web-embed"]
    command:  -p ws -c 22020 -d /etc/easytier/easytier-web/db/easytier-web.db -a 11211 -l 11210
    restart: always
    ports:
      - "22020:22020"
      - "11210:11210"
      - "11211:11211"

```

![Image](https://github.com/user-attachments/assets/e9b82e4f-4988-47c0-b300-10da98c53b5d)
