### ISSUE TITLE
大数据量传输时，远程代理会掉线

### ISSUE THREAD

**Issue by guojingfeng1994** [EasyTier/EasyTier#319]
首先项目非常好用，感谢作者的辛勤付出。
最近在组局域网，使用了这个项目，大概是这样的：
我有两个局域网A和B，中转服务器为阿里云的服务器C，其中A和B都配置了子网代理。
我的工作环境在B，使用的window GUI版，开发服务器在A，系统是ubuntu 22.04，用的docker部署。
正常工作使用都是没有问题的，但是当出现数据库数据较多时，或者导出大表时，大概数据有1.6G吧，到一半的过程必定会出现中断，A掉线，并且不会自动起来，必须重启docker容器才能重新连接。
我试了很多次都会这样，不知道是不是在数据量大的时候，docker部署的方式有什么限制

**Comment by KKRainbow** [comment]
可以开启一下 log 么，断线的时候把 log 发给我

 --file-log-level info

**Comment by KKRainbow** [comment]
听着像是有比较严重的 bug

**Comment by guojingfeng1994** [comment]
> 可以开启一下 log 么，断线的时候把 log 发给我
> 
> --file-log-level info

```yaml

version: "3.8"
services:
   easytier:
         #labels:
         #      com.centurylinklabs.watchtower.enable: "true"        
         privileged: true
         restart: always
         mem_limit: 0m
         container_name: easytier
         hostname: easytier
         #network_mode: host
         volumes:
               - /etc/easytier:/root
         environment:
               - TZ=Asia/Shanghai
         image: easytier/easytier:v1.2.3
         ports:
            - "13030:13030/tcp"
            - "13031:13031/tcp"
            - "13032:13032/tcp"
            - "13030:13030/udp"
            - "13031:13031/udp"
            - "13032:13032/udp"
         command: -i xx.xxx.11.1 --network-name abc --network-secret abc -n 192.168.45.0/24 --peers udp://abc.com:13030  -l 13030
```

@KKRainbow 我的局域网A的docker compose文件大概是这样的，是在command后面追加--file-log-level info吗？

command: -i xx.xxx.11.1 --network-name abc --network-secret abc -n 192.168.45.0/24 --peers udp://abc.com:13030  -l 13030 --file-log-level info
