### ISSUE TITLE
[bug] 配置文件启动如何配置 vpn-portal？

### ISSUE THREAD

**Issue by Saoforest** [EasyTier/EasyTier#346]
### 描述问题 / Describe the bug

使用一键脚本安装的 easytier，无法按照官网方式添加--vpn-portal 开启 wireguard 支持，请问配置文件有相关配置吗？

**Comment by KKRainbow** [comment]
可以先用命令行启动下，会打印配置文件

**Comment by LGinC** [comment]
```toml
[vpn_portal_config]
client_cidr = "192.168.2.0/24"
wireguard_listen = "0.0.0.0:42314"
```

等效于
`--vpn-portal wg://0.0.0.0:42314/192.168.2.0/24`
