### ISSUE TITLE
[bug] mac会默认添加一条10.0.0.0/24的路由

### ISSUE THREAD

**Issue by lRoccoon** [EasyTier/EasyTier#604]
### 描述问题 / Describe the bug

现象：
在启动easytier后，mac的路由表会增加一条新的路由：

![Image](https://github.com/user-attachments/assets/dfeb1389-b93e-4dd0-aa34-7890dfb825e2)

配置文件：
```toml
instance_name = "macbook"
hostname = "macbook"
instance_id = "***"
ipv4 = "192.168.11.31"
dhcp = false
routes = ["192.168.11.0/24"]
listeners = []
exit_nodes = []
rpc_portal = "127.0.0.1:15888"

[network_identity]
network_name = "***"
network_secret = "***"

[[peer]]
uri = "***"

[vpn_portal_config]
client_cidr = "192.168.11.0/24"
wireguard_listen = "0.0.0.0:11012"

[flags]
default_protocol = "tcp"
dev_name = ""
enable_encryption = true
enable_ipv6 = true
mtu = 1380
latency_first = true
enable_exit_node = false
no_tun = false
use_smoltcp = false
foreign_network_whitelist = "*"
```

### 重现步骤 / Reproduction

可以直接使用easytier-gui在mac启动

### 预期结果 / Expected behavior

默认应该创建节点虚拟IP所在子网的路由，在手动指定routes时，应该仅创建手动指定的路由
例如，当前配置文件中虚拟IP子网为 192.168.11.0/24
