### ISSUE TITLE
[bug] Peer id conflict

### ISSUE THREAD

**Issue by soulwhisper** [EasyTier/EasyTier#609]
### 描述问题 / Describe the bug

以下是我的config.toml，该节点A在防火墙内转发三个内网网段，通过容器方式启动easytier后报错。
############### TOML ###############

instance_name = "default"
dhcp = true
listeners = [
    "tcp://0.0.0.0:11010",
    "udp://0.0.0.0:11010",
    "wg://0.0.0.0:11011",
    "ws://0.0.0.0:11011/",
    "wss://0.0.0.0:11012/",
]
mapped_listeners = []
exit_nodes = []
rpc_portal = "0.0.0.0:15888"

[network_identity]
network_name = "$NETWORK_NAME"
network_secret = "$NETWORK_SECRET"

[[peer]]
uri = "tcp://public.easytier.top:11010"

[[proxy_network]]
cidr = "10.0.0.0/24"

[[proxy_network]]
cidr = "10.10.0.0/24"

[[proxy_network]]
cidr = "10.20.0.0/24"

[flags]
enable_kcp_proxy = true
latency_first = true

报错信息如下：
2025-02-07 18:40:45: new peer added. peer_id: 2925231149
2025-02-07 18:40:46: tun device ready. dev: tun0
2025-02-07 18:40:46: dhcp ip changed. old: None, new: Some(10.126.126.2/24)
2025-02-07 18:40:59: connection error. local: tcp://0.0.0.0:11010, remote: tcp://10.88.0.1:44167, err: wait resp error: peer id conflict
2025-02-07 18:41:00: new connection accepted. local: tcp://0.0.0.0:11010, remote: tcp://10.88.0.1:41701
2025-02-07 18:41:00: connection error. local: tcp://0.0.0.0:11010, remote: tcp://10.88.0.1:41701, err: wait resp error: peer id conflict
2025-02-07 18:41:02: new connection accepted. local: tcp://0.0.0.0:11010, remote: tcp://10.88.0.1:46533
2025-02-07 18:41:02: connection error. local: tcp://0.0.0.0:11010, remote: tcp://10.88.0.1:46533, err: wait resp error: peer id conflict
2025-02-07 18:41:06: new connection accepted. local: tcp://0.0.0.0:11010, remote: tcp://10.88.0.1:43455
2025-02-07 18:41:06: connection error. local: tcp://0.0.0.0:11010, remote: tcp://10.88.0.1:43455, err: wait resp error: peer id conflict
2025-02-07 18:41:32: new connection accepted. local: udp://0.0.0.0:11010, remote: udp://10.88.0.1:47516
2025-02-07 18:41:32: connection error. local: udp://0.0.0.0:11010, remote: udp://10.88.0.1:47516, err: wait resp error: peer id conflict
2025-02-07 18:41:34: new connection accepted. local: udp://0.0.0.0:11010, remote: udp://10.88.0.1:50080
2025-02-07 18:41:34: connection error. local: udp://0.0.0.0:11010, remote: udp://10.88.0.1:50080, err: wait resp error: peer id conflict
2025-02-07 18:41:36: new connection accepted. local: udp://0.0.0.0:11010, remote: udp://10.88.0.1:33264
2025-02-07 18:41:36: connection error. local: udp://0.0.0.0:11010, remote: udp://10.88.0.1:33264, err: wait resp error: peer id conflict
2025-02-07 18:41:39: new connection accepted. local: udp://0.0.0.0:11010, remote: udp://10.88.0.1:42224
2025-02-07 18:41:39: connection error. local: udp://0.0.0.0:11010, remote: udp://10.88.0.1:42224, err: wait resp error: peer id conflict
2025-02-07 18:41:59: new connection accepted. local: wg://0.0.0.0:11011, remote: wg://10.88.0.1:52144
2025-02-07 18:41:59: connection error. local: wg://0.0.0.0:11011, remote: wg://10.88.0.1:52144, err: wait resp error: peer id conflict
2025-02-07 18:41:59: new connection accepted. local: wg://0.0.0.0:11011, remote: wg://10.88.0.1:58598
2025-02-07 18:41:59: connection error. local: wg://0.0.0.0:11011, remote: wg://10.88.0.1:58598, err: wait resp error: peer id conflict
2025-02-07 18:42:00: new connection accepted. local: wg://0.0.0.0:11011, remote: wg://10.88.0.1:52139
2025-02-07 18:42:00: connection error. local: wg://0.0.0.0:11011, remote: wg://10.88.0.1:52139, err: wait resp error: peer id conflict
2025-02-07 18:42:03: new connection accepted. local: wg://0.0.0.0:11011, remote: wg://10.88.0.1:49820
2025-02-07 18:42:03: connection error. local: wg://0.0.0.0:11011, remote: wg://10.88.0.1:49820, err: wait resp error: peer id conflict
2025-02-07 18:42:33: new connection accepted. local: ws://0.0.0.0:11011/, remote: ws://10.88.0.1:38239/
2025-02-07 18:42:33: connection error. local: ws://0.0.0.0:11011/, remote: ws://10.88.0.1:38239/, err: wait resp error: peer id conflict
2025-02-07 18:42:34: new connection accepted. local: ws://0.0.0.0:11011/, remote: ws://10.88.0.1:41439/
2025-02-07 18:42:34: connection error. local: ws://0.0.0.0:11011/, remote: ws://10.88.0.1:41439/, err: wait resp error: peer id conflict
2025-02-07 18:42:35: new connection accepted. local: ws://0.0.0.0:11011/, remote: ws://10.88.0.1:42733/
2025-02-07 18:42:35: connection error. local: ws://0.0.0.0:11011/, remote: ws://10.88.0.1:42733/, err: wait resp error: peer id conflict
2025-02-07 18:42:40: new connection accepted. local: ws://0.0.0.0:11011/, remote: ws://10.88.0.1:38343/
2025-02-07 18:42:40: connection error. local: ws://0.0.0.0:11011/, remote: ws://10.88.0.1:38343/, err: wait resp error: peer id conflict
2025-02-07 18:43:07: new connection accepted. local: wss://0.0.0.0:11012/, remote: wss://10.88.0.1:37081/
2025-02-07 18:43:07: connection error. local: wss://0.0.0.0:11012/, remote: wss://10.88.0.1:37081/, err: wait resp error: peer id conflict

### 重现步骤 / Reproduction

使用podman 运行 easytier/easytier:latest,
option="--privileged  --network=host", 
cmd="-c config.toml", 
注意同目录下应有.env文件包含NETWORK_NAME和NETWORK_SECRET。

### 预期结果 / Expected behavior

无报错，外网节点可连接内网

**Comment by KKRainbow** [comment]
啥版本

**Comment by yushangcl** [comment]
我今天也发我了这个问题。可以ping通。但是无法http或者ssh访问。2.2.1版本

**Comment by KKRainbow** [comment]
虚拟网内所有版本都是221吗

**Comment by yushangcl** [comment]
> 虚拟网内所有版本都是221吗

是的，两台小米路由器。版本都事221。但是windows版本的似乎可以正常访问其他节点

**Comment by soulwhisper** [comment]
好像区分不同的网络状况有不同的结果，上面第一次测试是联通手机热点的MacbookAir，这个连接内网SSH通了。第二次测试是公司内网有防火墙的跳板机，这个连不上，超时了。

**Comment by JsonSong89** [comment]
感觉是 et上报自己节点的监听地址有问题,
第一次报错 
2025-04-28 10:51:54: connection error. local: ws://0.0.0.0:11011/, remote: ws://172.20.0.1:43859/, err: wait resp error: peer id conflict
172.20.0.1是我另外一个docker-compose的网段
我直接销毁172.20.0.1这个容器之后,重启et 
然后又报错:
2025-04-28 10:51:54: connection error. local: ws://0.0.0.0:11011/, remote: ws://172.21.0.1:43859/, err: wait resp error: peer id conflict

et使用docker部署 网络是host模式



![Image](https://github.com/user-attachments/assets/bfe0e705-ec0b-4d98-8963-bce960a1ca70)

**Comment by cuiko** [comment]
P1 <-> S <-> P2
P2 连 P1，ssh 通过，P1 上的 http 服务能访问

S 的配置是
```yaml
services:
  watchtower: # 用于自动更新easytier镜像，若不需要请删除这部分
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - WATCHTOWER_NO_STARTUP_MESSAGE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup --label-enable
  easytier:
    image: easytier/easytier:latest # 国内用户可以使用 m.daocloud.io/docker.io/easytier/easytier:latest
    hostname: easytier
    container_name: easytier
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /etc/machine-id:/etc/machine-id:ro # 映射宿主机机器码
      - /etc/easytier:/root
    command: -i <ip> --network-name <用户> --network-secret <密码> -p tcp://<服务器地址>:11010
```

但 S 的 log 一直弹
```text
easytier    | 2025-04-29 12:45:59: connection error. local: tcp://0.0.0.0:11010, remote: tcp://<服务器地址>:34931, err: wait resp error: peer id conflict
easytier    | 2025-04-29 12:45:59: connect to peer error. dst: tcp://<服务器地址>:11010, ip_version: V4, err: Err(WaitRespError("peer id conflict"))
```
