### ISSUE TITLE
[bug] 在双网卡主板上，在默认情况下会创建多个tun设备（多个节点）

### ISSUE THREAD

**Issue by 3RDNature** [EasyTier/EasyTier#618]
### 描述问题 / Describe the bug

主板是ASRACK X470D4U，主板上有两个网卡，被unraid启用绑定并被设定为主动备份（如下图）

![Image](https://github.com/user-attachments/assets/58fa5bdc-d6c4-4c23-8ae2-24413048291f)

在未设定配置中的【dev_name】的时候，会创建多个tun设备，如下图

![Image](https://github.com/user-attachments/assets/01690379-4eb2-4988-97a3-b7e7e18c098b)

此时在在网络内其他设备、本地运行easytier-cli peer的时候会出现两个一模一样的节点，如下图

![Image](https://github.com/user-attachments/assets/6af8c131-4b03-433c-be54-3827151c87c6)

### 重现步骤 / Reproduction

在未设定配置中的【dev_name】的时候，会创建多个tun设备，如下图

![Image](https://github.com/user-attachments/assets/01690379-4eb2-4988-97a3-b7e7e18c098b)

此时在在网络内其他设备、本地运行easytier-cli peer的时候会出现两个一模一样的节点，如下图

![Image](https://github.com/user-attachments/assets/6af8c131-4b03-433c-be54-3827151c87c6)

手动设置【dev_name】为naturenetwork时，问题消失。

附目前的config.toml

```toml
ipv4 = "172.16.255.2"
dhcp = false
listeners = [
    "tcp://0.0.0.0:20199",
    "udp://0.0.0.0:20199",
]
exit_nodes = []
rpc_portal = "127.0.0.1:15888"

[[peer]]
uri="tcp://[deleted]"

[network_identity]
network_name = "[deleted]"
network_secret = "[deleted]"

[flags]
default_protocol = "tcp"
dev_name = "naturenetwork"  # 在此处设定了dev_name后，检测到重复的tun设备就好了
enable_encryption = true
enable_ipv6 = false
mtu = 1380
latency_first = false
enable_exit_node = true
no_tun = false
use_smoltcp = false
foreign_network_whitelist = "[deleted]"
disable_p2p = false
relay_all_peer_rpc = false
disable-udp-hole-punching = true
multi-thread = true
```

希望能够修复这个bug，感激不尽！
