### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by XDwanj** [EasyTier/EasyTier#680]
### 描述问题 / Describe the bug

我有两台服务器作为中转，然后我给所有节点，包括服务器（服务器不参与局域网内）都加上 `-p tcp://public.easytier.top:10010` 重启整个网络以后，两台主机用千兆网口+超五类网线连接进行测速，减少了接近四分之一的带宽

![Image](https://github.com/user-attachments/assets/f8f44f9b-b356-4530-8e43-cecdba643138)

![Image](https://github.com/user-attachments/assets/40cd3b51-c9d0-459a-849c-d00f02fc7104)

### 重现步骤 / Reproduction

Gmk （小主机 Linux

```yaml
  easytier-sakura-server:
    container_name: easytier-sakura-server
    restart: always
    environment:
      - TZ=Asia/Shanghai
    image: easytier/easytier:latest
    ports:
      - 11010:11010/tcp
    command: >
      --no-tun
      --hostname sakura
      -l tcp://0.0.0.0:11010
      -p tcp://public.easytier.top:10010   # 官网节点
      --relay-network-whitelist "xxxxxxx"
      -r 11111
  easytier-nilou-server:
    container_name: easytier-nilou-server
    restart: always
    environment:
      - TZ=Asia/Shanghai
    image: easytier/easytier:latest
    ports:
      - 11011:11010/tcp
    command: >
      --no-tun
      --hostname nilou
      -l tcp://0.0.0.0:11010
      -p tcp://public.easytier.top:10010  # 官网节点
      --relay-network-whitelist "xxxxxxx"
      -r 11112
  easytier:
    container_name: easytier
    restart: always
    privileged: true
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    image: easytier/easytier:latest
      # --no-listener
    command: >
      -i 10.10.10.3
      --dev-name et
      --hostname Gmk
      --network-name xxxxxxx
      --network-secret xxxxxxx
      -l tcp://0.0.0.0:10000
      -p tcp://localhost:11010
      -p tcp://localhost:11011
      -p tcp://public.easytier.top:10010 # 官网节点
      -r 22222
 ```

Manjaro （笔记本 Linux

```yaml
  easytier:
    restart: always
    privileged: true
    container_name: easytier
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    image: easytier/easytier:latest
    command: >
      -i 10.10.10.1
      --dev-name easytier
      --hostname Manjaro
      --network-name xxxxxx
      --network-secret xxxxxx
      --no-listener
      --rpc-portal 22222
      -p tcp://gmk.local:10000  # 10.42.0.1 局域网中 Gmk 的 IP，Gmk 和 Manjaro 用网线连接
      -p tcp://frp-gap.com:10585
      -p tcp://jp2.nilou.moe:10001
      -p tcp://public.easytier.top:11010 # 官网节点
```

### 预期结果 / Expected behavior

既然公共服务只对打洞进行帮助，那打洞后的带宽表现应该与加入公共节点前一致才对
