### ISSUE TITLE
[bug] p2p失败

### ISSUE THREAD

**Issue by catch6** [EasyTier/EasyTier#959]
### 描述问题 / Describe the bug

目前网络是4个位于不同地方主机，不同的网络，p2p全部失败，请帮我看下是哪步不正确吗

<img width="836" alt="Image" src="https://github.com/user-attachments/assets/c034f75d-e5c5-4de2-a676-b0f165285f83" />

高级配置使用的默认配置

<img width="484" alt="Image" src="https://github.com/user-attachments/assets/07ce3f46-80b9-42a8-a2cd-fc678334892d" />

自建服务器docker-compose
```yaml
services:
  easytier:
    image: registry.cn-beijing.aliyuncs.com/catch-public/easytier-easytier:latest
    container_name: easytier
    restart: unless-stopped
    user: root
    privileged: true
    network_mode: host
    hostname: tx-1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - 'TZ=Asia/Shanghai'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - './data:/root'
      - '/etc/machine-id:/etc/machine-id:ro'
    command: >
      --enable-kcp-proxy
```
每个节点的docker-compose

<img width="826" alt="Image" src="https://github.com/user-attachments/assets/19c99bc7-c98d-4aab-8193-5d12cfc19ff8" />
